### ISSUE TITLE
pub.dev update for latest release 3.0.3?

### ISSUE THREAD

**Issue by koraybalci** [advoques/document_file_save_plus#18]
Hi, 

I see that there is a new release with the fixes here but no updates yet in https://pub.dev/packages/document_file_save_plus/versions. 

When do you plan an update?

**Comment by sirpengi** [comment]
I'm in favour of this being updated on pub.dev, but for those waiting for this, you can work around this by setting a specific git tag as a dependency. My `pubspec.yaml` has this:

```
  document_file_save_plus:
    git:
      url: https://github.com/advoques/document_file_save_plus.git
      ref: 3.0.3
```
